#pragma once

// Auto-generated by calibrate.py — do not edit by hand.
// Re-run ./run_calibration.sh to regenerate.
//
// Decoupling matrix: maps 9 baseline-subtracted sensor deltas -> 6 DOF outputs.
// Rows: TX, TY, TZ, RX, RY, RZ  |  Cols: mag1x,y,z  mag2x,y,z  mag3x,y,z

namespace Config {

const float DECOUPLING_M[6][9] = {
    {   19.457392f,    2.677925f,    1.287297f,    4.289317f,    4.236134f,   -0.373639f,  -37.840089f,  -10.728957f,  -12.103615f },  // TX
    {  -21.738892f,  -30.567704f,   -7.554124f,   -3.229489f,   17.044860f,   14.066056f,  -17.595508f,   42.300673f,   -8.491517f },  // TY
    {   18.093357f,   15.907547f,  -18.617622f,    4.372362f,    4.865319f,   -2.733806f,    1.837238f,  -12.453562f,   14.331466f },  // TZ
    {   21.312253f,   -7.693418f,   16.663125f,   -3.146800f,    3.474024f,   -1.716939f,    2.046350f,  -15.825964f,    0.212285f },  // RX
    {  -30.173631f,    7.044647f,   -6.368458f,  -33.165860f,    0.086986f,   21.645966f,    5.918728f,  -28.502949f,  -56.012918f },  // RY
    {   12.810782f,    5.714678f,   -7.274197f,   -3.556497f,   -1.579326f,    2.089405f,   -2.886261f,   10.714859f,    2.389068f }   // RZ
};

}  // namespace Config
