#pragma once

// Auto-generated by calibrate.py — do not edit by hand.
// Re-run ./run_calibration.sh to regenerate.
//
// Decoupling matrix: maps 9 baseline-subtracted sensor deltas -> 6 DOF outputs.
// Rows: TX, TY, TZ, RX, RY, RZ  |  Cols: mag1x,y,z  mag2x,y,z  mag3x,y,z

namespace Config {

const float DECOUPLING_M[6][9] = {
    {   -6.364029f,  -13.454822f,   13.970098f,    8.856643f,    3.000698f,   -1.868354f,  -39.706781f,   -3.921719f,  -17.317701f },  // TX
    {  -12.637182f,  -57.227019f,   24.634812f,   -1.819123f,   15.311991f,    5.532673f,    7.710322f,   65.836016f,   27.474965f },  // TY
    {   45.831711f,  -27.614711f,    8.100727f,   -4.779119f,   25.831718f,    8.277450f,  -33.431008f,   -1.803317f,   -9.337185f },  // TZ
    {   -2.489711f,  -15.864864f,    5.224985f,   -0.091222f,    2.831745f,    0.953790f,    0.339547f,    9.649729f,    2.081359f },  // RX
    {  -21.456696f,   36.337341f,  -28.179020f,  -32.265994f,   -9.458103f,    2.257165f,   89.453338f,   -2.280939f,   55.314277f },  // RY
    {   18.233395f,  -11.705598f,    2.748724f,   -7.777041f,    0.882662f,    4.890665f,   -1.604835f,   29.719320f,    7.295976f },  // RZ
};

}  // namespace Config
